name: Daily Report Generation

on:
  workflow_dispatch:  # allow manual run
  schedule:
    - cron: "5 18 * * *"  # daily at 18:05 UTC

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      # Checkout full history
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Pull latest changes to ensure up-to-date repo
      - name: Pull latest changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase

      # Generate report
      - name: Generate daily report
        id: report
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          echo "Daily Report for $TODAY" > daily_report.log
          echo "==========================" >> daily_report.log

          COMMITS=$(git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --pretty=format:"%h - %s")

          if [ -z "$COMMITS" ]; then
            echo "No new files were added today." >> daily_report.log
          else
            echo "Commits:" >> daily_report.log
            echo "$COMMITS" >> daily_report.log
            echo "" >> daily_report.log

            FILES=$(git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --name-status --pretty=format: | grep '^A' | awk '{print $2}')

            if [ -n "$FILES" ]; then
              echo "Files added today:" >> daily_report.log
              echo "$FILES" | sort | uniq >> daily_report.log
            else
              echo "No new files were added today." >> daily_report.log
            fi
          fi

          echo "" >> daily_report.log
          echo "End of report." >> daily_report.log

      # Commit and push report
      - name: Commit and push report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add daily_report.log
          git commit -m "Daily report for $(date -u +"%Y-%m-%d")" || echo "No changes to commit"
          git push origin main
