name: Daily Report Generation

on:
  schedule:
    # Runs every day at 13:05 EST (18:05 UTC)
    - cron: "5 18 * * *"

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Fetch today's commits and files
      - name: Generate daily report
        id: report
        run: |
          # Get the current date in YYYY-MM-DD format
          TODAY=$(date -u +"%Y-%m-%d")

          # Get the list of commits from today
          COMMITS=$(git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --pretty=format:"%h - %s")
          
          # Initialize report content
          echo "Daily Report for $TODAY" > daily_report.log
          echo "==========================" >> daily_report.log

          # Check if there were any commits
          if [ -z "$COMMITS" ]; then
            echo "No new files were added today." >> daily_report.log
          else
            echo "Commits:" >> daily_report.log
            echo "$COMMITS" >> daily_report.log
            echo "" >> daily_report.log
          
            # Get the list of files added in today's commits
            FILES=$(git log --since="$TODAY 00:00:00" --until="$TODAY 23:59:59" --name-status --pretty=format: | grep '^A' | awk '{print $2}')
            
            if [ -n "$FILES" ]; then
              echo "Files added today:" >> daily_report.log
              echo "$FILES" | sort | uniq >> daily_report.log
            else
              echo "No new files were added today." >> daily_report.log
            fi
          fi
          
          echo "" >> daily_report.log
          echo "End of report." >> daily_report.log

      # Step 3: Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 4: Pull and rebase the latest changes
      - name: Pull and rebase
        run: |
          git fetch origin main
          git rebase origin/main

      # Step 5: Commit and push the report
      - name: Commit and push report
        run: |
          git add daily_report.log
          git commit -m "Daily report for $TODAY" || echo "No changes to commit"
          git push origin main
